name: build-wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-wheels:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    container: quay.io/pypa/manylinux2014_x86_64:2024-07-02-9ac04ee

    steps:
    - uses: actions/checkout@v2
    - name: Build Wheels
      run:  |
            yum -y install wget
            yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel
            wget "https://github.com/bazelbuild/bazel/releases/download/5.1.0/bazel-5.1.0-installer-linux-x86_64.sh" -O bazel-5.1.0-installer-linux-x86_64.sh
            chmod +x bazel-5.1.0-installer-linux-x86_64.sh
            ./bazel-5.1.0-installer-linux-x86_64.sh --user
            export PATH=$PATH:~/.bazel/bin
            export PYTHON_BIN_PATH='/opt/python/cp38-cp38/bin/python'
            bash build_wheels.sh
            echo "Built successfully."
            echo `pwd`

    - name: Archive pygloo-wheels
      uses: actions/upload-artifact@v4
      with:
        name: pygloo_python3X_wheels_on_manylinux
        path: dist/*
